#log日志配置
#logging:
#  config: classpath:config/logback.xml
#内嵌服务器的配置
server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 10

#系统配置文件
system-config:
  system-name: "社区讨论系统"
  page-name: "系统登录"

#spring的配置
spring:
  aop:
    auto: false
  datasource:
   driver-class-name: com.mysql.jdbc.Driver
   type: com.alibaba.druid.pool.DruidDataSource
   initialSize: 1
   maxActive: 20
   minIdle: 3
   maxWait: 60000
   timeBetweenEvictionRunsMillis: 60000
   minEvictableIdleTimeMillis: 300000
   validationQuery: SELECT 'x'
   testWhileIdle: true
   testOnBorrow: false
   testOnReturn: false
   poolPreparedStatements: true
   maxPoolPreparedStatementPerConnectionSize: 20
   filters: stat,wall,slf4j
   connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
   url: jdbc:mysql://127.0.0.1:3306/demo-git?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#   url: jdbc:mysql://us-cdbr-iron-east-01.cleardb.net/ad_ce069907811882b?user=b0949dea6dd7b9&password=e73f2288
   username: root
   password: newpassword

  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true

  thymeleaf:
   cache: false