#log日志配置
logging:
  config: classpath:config/logback.xml
#内嵌服务器的配置
server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8
  ### 设置session失效时长
  servlet:
    session:
      timeout: 60

#系统配置文件
system-config:
  system-name: "社区讨论系统"
  page-name: "系统登录"
  vm-path: "vm/xml_object.vm"

#spring的配置
spring:
  aop:
    auto: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    maxActive: 20
    minIdle: 3
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    url: jdbc:mysql://127.0.0.1:3306/bootdo?useUnicode=true&characterEncoding=utf8
    username: root
    password: newpassword

  ### 配置http请编码，防止出现乱码问题
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true

  thymeleaf:
    cache: false
#    servlet:
#      content-type: text/html
#    mode: LEGACYHTML5

mybatis:
  configuration:
    callSettersOnNulls: true
    ##驼峰命名转化
    map-underscore-to-camel-case: true